name: build package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - name: Add dist directory to git
      - name: Create a tarball
        run: tar -czvf release.tar.gz dist src package.json README.md
      - name: Create Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: Release ${{ github.ref }}